// frontend/src/App.vue
<script setup>
// import { RouterLink, RouterView } from 'vue-router'
// import HelloWorld from './components/HelloWorld.vue'
import NavbarIndex from './components/navbar/NavbarIndex.vue'
import FooterIndex from './components/footer/FooterIndex.vue'
</script>

<template>
  <div class="mdk-header-layout js-mdk-header-layout">
    <!-- Header -->
    <div id="header" class="mdk-header js-mdk-header mb-0" data-fixed data-effects="">
      <div class="mdk-header__content">

        <!-- Navbar -->

        <NavbarIndex  class="btn"/>

        <!-- // END Navbar -->

      </div>
    </div>

    <!-- // END Header -->

    <!-- Header Layout Content -->
    <div class="mdk-header-layout__content page-content ">

      <!-- Replace this with your page content -->

      <div class="container page__container flex d-flex my-32pt">
          <div class="container" style="height: 50vh;">
            <H1>hola</H1>
            <button @click="abrir">
              Abrir
            </button>
          </div>
      </div>

      <!-- // END Replace this with your page content -->

    </div>
    <!-- // END Header Layout Content -->

    <!-- Footer -->

    <FooterIndex />

    <!-- // END Footer -->

  </div>
  <!-- // END Header Layout -->

  <!-- Drawer -->
  <div class="mdk-drawer js-mdk-drawer" id="default-drawer" data-align="start" data-position="left" data-domfactory-upgraded="mdk-drawer" :data-opened="drawer ? '' : null"><div class="mdk-drawer__scrim" style="" @click="drawer = false"></div>
        
  <div class="mdk-drawer__content" >
            <div class="sidebar sidebar-dark-pickled-bluewood sidebar-left " data-perfect-scrollbar>

                <!-- Sidebar Content -->

                <a href="index.html" class="sidebar-brand ">
                    <!-- <img class="sidebar-brand-icon" src="../../public/images/illustration/student/128/white.svg" alt="Luma"> -->

                    <span class="avatar avatar-xl sidebar-brand-icon h-auto">

                        <span class="avatar-title rounded bg-primary"><img
                                src="../images/illustration/student/128/white.svg" class="img-fluid" alt="logo" /></span>

                    </span>

                    <span>Luma</span>
                </a>

                <div class="application-shell-content">
                    <span class="sidebar-text">Hola</span>
                </div>

                <!-- // END Sidebar Content -->

            </div>
        </div>
    </div>
</template>
<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "App",
  components: {
    NavbarIndex,
  },
  data() {
    return {
      drawer: false,
    };
  },
  mounted() {
    
  },
  methods: {
    abrir() {
      // data-opened="" agregar esta propiedad al div con id="default-drawer"
      this.drawer = !this.drawer;
      
    },
    cerrar(event) {
    if (this.drawer) {
      const target = event.target.closest('#default-drawer');
      if (!target) {
        this.drawer = "";
      }
    }
  },
    // hacer la funcion para cerrar el drawer cuando se haga click en cualquier parte de la pantalla


  },
  beforeMount() {
  document.removeEventListener('click', this.cerrar);
}
  
});
</script>

// talentia_angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { SidebarService } from './sidebar-service.service';
import { ApiService } from './services/api_service/api.service';
import { RolesService } from './services/roles/roles.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  template: `
    <div class="app-container">
      <div class="mdk-drawer js-mdk-drawer" id="default-drawer" id="default-drawer" [attr.data-opened]="sidebarOpened ? '' : null">
        <!-- Contenido del sidebar -->
      </div>
      <!-- Resto del contenido -->
    </div>
    `,
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
    // ver la url actual
    sidebarOpened = false; // Variable para mantener el estado del sidebar

  constructor(private sidebarService: SidebarService, public auth: ApiService, public rol:RolesService ) {}


  ngOnInit(): void {
    this.sidebarService.sidebarState$.subscribe((isOpened) => {
      this.sidebarOpened = isOpened;
    });
  }
  title = 'talentia_angular';
}


<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<div class="preloader">
  <div class="sk-chase">
      <div class="sk-chase-dot"></div>
      <div class="sk-chase-dot"></div>
      <div class="sk-chase-dot"></div>
      <div class="sk-chase-dot"></div>
      <div class="sk-chase-dot"></div>
      <div class="sk-chase-dot"></div>
  </div>

  <!-- <div class="sk-bounce">
<div class="sk-bounce-dot"></div>
<div class="sk-bounce-dot"></div>
</div> -->

  <!-- More spinner examples at https://github.com/tobiasahlin/SpinKit/blob/master/examples.html -->
</div>
<div class="mdk-drawer-layout js-mdk-drawer-layout" data-push data-responsive-width="992px">
  <div class="mdk-drawer-layout__content page-content">
    <app-nabvar></app-nabvar>
    <!-- <div class="container"> -->
    <router-outlet></router-outlet>
    <!-- </div> -->
    <app-footer></app-footer>
  </div>

  <!-- // END drawer-layout__content -->

  <!-- Drawer -->

  <!-- <app-sidebar></app-sidebar> -->
  <div class="mdk-drawer js-mdk-drawer" id="default-drawer" id="default-drawer"
    [attr.data-opened]="sidebarOpened ? '' : null">
    <div class="mdk-drawer__content" data-opened="">
      <div class="sidebar sidebar-dark-pickled-bluewood sidebar-left" data-perfect-scrollbar data-openeded>

        <!-- Sidebar Content -->

        <!-- <div class="d-flex align-items-center navbar-height">
          <form action="index.html" class="search-form search-form--black mx-16pt pr-0 pl-16pt">
            <input type="text" class="form-control pl-0" placeholder="Search">
            <button class="btn" type="submit"><i class="material-icons">search</i></button>
          </form>
        </div> -->

        <a href="/" class="sidebar-brand ">
          <!-- <img class="sidebar-brand-icon" src="../../public/images/illustration/student/128/white.svg" alt="Talentia"> -->
          <span class="avatar avatar-xl sidebar-brand-icon h-auto">
            <span class="avatar-title rounded bg-primary"><img src="assets/images/illustration/student/128/white.svg"
                class="img-fluid" alt="logo" /></span>
          </span>
          <span>Talentia</span>
        </a>

        <div class="">
          <div *ngIf="!auth.isLoggedIn()">
            <div class="sidebar-heading">Inicia Sesión</div>
            <ul class="sidebar-menu">
              <li class="sidebar-menu-item">
                <a class="sidebar-menu-button" href="/login">
                  <i class="fa-solid fa-right-to-bracket mr-2 sidebar-menu-icon--left"></i>
                  <!-- <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">home</span> -->
                  <span class="sidebar-menu-text">Login</span>
                </a>
              </li>
              <li class="sidebar-menu-item">
                <a class="sidebar-menu-button" href="/signup">
                  <i class="fa-solid fa-user-plus mr-2 sidebar-menu-icon--left"></i>
                  <!-- <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">home</span> -->
                  <span class="sidebar-menu-text">Sign Up</span>
                </a>
              </li>
            </ul>
          </div>
          <div *ngIf="auth.isLoggedIn()">
          <!-- Instructor sidebar -->
            <div *ngIf="rol.getRoles() == 'ADMIN'">

                <div class="sidebar-heading" >ADMIN</div>
                <ul class="sidebar-menu">

                  <li class="sidebar-menu-item">
                    <a class="sidebar-menu-button" href="/edit-courses">
                      <i class="fa-solid fa-pen-to-square mr-2 sidebar-menu-icon--left"></i>
                    <!-- <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">home</span> -->
                    <span class="sidebar-menu-text">Gestión de cursos</span>
                  </a>
                </li>
                <!-- <li class="sidebar-menu-item">
                  <a class="sidebar-menu-button"
                  href="/courses">

                  <i class="fa-solid fa-graduation-cap mr-2 sidebar-menu-icon--left"></i>
                  <span class="sidebar-menu-text">Cursos</span>
                </a>
              </li> -->
            </ul>
          </div>
          <div *ngIf="rol.getRoles() == 'USER'">

            <div class="sidebar-heading">USUARIO</div>
            <ul class="sidebar-menu">
              <li class="sidebar-menu-item">
                <a class="sidebar-menu-button" href="/courses">

                  <i class="fa-solid fa-graduation-cap mr-2 sidebar-menu-icon--left"></i>
                  <!-- <span class="material-icons sidebar-menu-icon sidebar-menu-icon--left">home</span> -->
                  <span class="sidebar-menu-text">Cursos</span>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>

        <!-- // END Sidebar Content -->

      </div>
    </div>
  </div>


  <!-- // END Drawer -->

</div>



<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced. * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
